### ISSUE TITLE
Support for autoclosing UX tag

### ISSUE THREAD

**Issue by Sunjammer** [fusetools/Fuse.AtomPlugin#28] opened 2016-11-09 21:50 UTC
UX is nice but manually writing the UX close tags all the time is a speedbump. Having automatic close of tags can be done via plugins that do it on keystroke but i'm not impressed with that approach. Having the plugin autoclose when a tag is left open, say when the > is typed but no /> would be a real speedup to workflow IMO.

**Comment by jsbeckr** [comment] 2016-12-17 19:42
Would be nice indeed. The old autoclose plugin is a bit buggy this package is much better and works as intended: https://atom.io/packages/autoclose-tags

**Comment by jsbeckr** [comment] 2017-01-17 10:10
Shouldn't we close this Issue then? (See the conversation in my PR)

**Comment by Tapped** [comment] 2017-01-17 10:21
Yeah, I agree

**Closed as completed by Tapped** 2017-01-17 10:21 UTC
